// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hellothere.proto

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string response = 1;</code>
   */
  boolean hasResponse();
  /**
   * <code>required string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>required string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
