// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hellothere.proto

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 number = 2;</code>
   */
  boolean hasNumber();
  /**
   * <code>required int32 number = 2;</code>
   */
  int getNumber();
}
